### ISSUE TITLE
[Critical, Safari] Can't use the site in Safari

### ISSUE THREAD

**Issue by oliverchan0222** [skygear-demo/react-chat-demo#26]
No response to click any button
![screen shot 2017-02-21 at 3 43 47 pm](https://cloud.githubusercontent.com/assets/20634676/23155292/fceb374e-f84c-11e6-88eb-49d9b2c87ba5.png)
![screen shot 2017-02-21 at 3 44 27 pm](https://cloud.githubusercontent.com/assets/20634676/23155293/fd2c84ba-f84c-11e6-98eb-3f232cf3ab7e.png)

**Comment by mayyuen318** [comment]
The conversation can't be loaded still. Kindly help check a bit~
