### ISSUE TITLE
[Minor] Empty message shouldn't be sent

### ISSUE THREAD

**Issue by oliverchan0222** [skygear-demo/react-chat-demo#30]
![screen shot 2017-02-21 at 3 58 49 pm](https://cloud.githubusercontent.com/assets/20634676/23155703/b7fd8d06-f84e-11e6-927d-669220503bac.png)

**Comment by mayyuen318** [comment]
<img width="1280" alt="screen shot 2017-02-22 at 1 48 52 pm" src="https://cloud.githubusercontent.com/assets/7130966/23198951/e288b570-f905-11e6-9530-02bad8905680.png">

Boris, 
Right now, the sender won't see them sending empty message. But when the sender presses 'send', the receiver still receive empty messages (not in real time but see after refreshing the page). 
Could you check and solve this issue again

**Comment by mayyuen318** [comment]
Sorry, clarify, both senders and receivers can still send and receive empty messages.

**Comment by akiroz** [comment]
doesn't happen on master branch, hosted version is outdated.
