### ISSUE TITLE
[Major, Sign up] All buttons/ fields become disabled

### ISSUE THREAD

**Issue by oliverchan0222** [skygear-demo/react-chat-demo#37]
During the sign-up process, if my 'Confirm Password" does not match with my "Password". Error message would pop up. After clicking ok for the error message, I cannot re-enter my "Confirm Password" or "Password", the page simply frozen.
![screen shot 2017-02-21 at 4 55 36 pm](https://cloud.githubusercontent.com/assets/20634676/23157538/a57815fe-f856-11e6-9bd2-f5f0f22ebe7f.png)

**Comment by mayyuen318** [comment]
This is known issue and already open a card for that. I will merge two cards together. 
Thanks!
