### ISSUE TITLE
[Major, Chat] Should scroll to the latest message automatically when user receive new message

### ISSUE THREAD

**Issue by oliverchan0222** [skygear-demo/react-chat-demo#38]
![screen shot 2017-02-21 at 5 00 33 pm](https://cloud.githubusercontent.com/assets/20634676/23157759/6a8bb436-f857-11e6-96a3-aefd4a778151.png)

**Comment by mayyuen318** [comment]
Known issue. Both message, conversation list and the popup of adding people are not scrollable at this moment. 

I will merge the cards together
